### ISSUE TITLE
[Feature Request]: DSA solution 4 to 10 

### ISSUE THREAD

**Issue by Yashgabani845** [CodeHarborHub/codeharborhub#324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description
currently inside lc soliution folder 3 probloem has solution 
i would like to add leetcode problem's solution from  problem number 4 to 10 numbers 
i will add proper markdown file with comments and documentation 

### Use Case

1. i will give multiple approch
2. in all 2 languages
3. proper description
4. iamges to understand properly

### Benefits

it will add solution freature to 5 problems 

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Yashgabani845** [comment]
@Ajay-Dhangar please assign me this issue

**Comment by Ajay-Dhangar** [comment]
Please follow our structure, similar to the source code of the [Two Sum problem](https://github.com/CodeHarborHub/codeharborhub/blob/main/dsa-solutions/lc-solutions/0000-0099/0001-two-sum.md?plain=1), to ensure better understanding for everyone. And [live preview](https://www.codeharborhub.live/dsa-solutions/lc-solutions/0000-0099/two-sum)

**Comment by Ajay-Dhangar** [comment]
I am assigning you a level 3 because I need high-quality content similar to the source code of the [Two Sum problem](https://github.com/CodeHarborHub/codeharborhub/blob/main/dsa-solutions/lc-solutions/0000-0099/0001-two-sum.md?plain=1). This assignment isn't just for one file but will be based on the quality of your content overall. If your content is good and valuable, I will also assign level 3 to your pull requests. Otherwise, I will assign level 2. I am assigning this issue level 3 because I need more valuable content.
